# action.yml
name: 'Broadcast'
description: 'Broadcast a message and record the time'
inputs:
  broadcast:  # id of input
    description: 'What would you like to broadcast?'
    required: true
    default: 'broadcast default'
  some_var:
    description: 'some_var description'
    required: true
    default: 'some_var default'
outputs:
  time: # id of output
    description: 'The timestamp of the broacasted message'
  foo:
    description: 'Pulumi Outputs'
    default: '_foo_ output default'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.broadcast }}
    - ${{ inputs.some_var }}