# action.yml
name: 'Broadcast'
description: 'Broadcast a message and record the time'
inputs:
  broadcast:  # id of input
    description: 'What would you like to broadcast?'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The timestamp of the broacasted message'
  tmp:
    description: 'Pulumi Outputs'
    default: 'default'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.broadcast }}